// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCqrZu-OsSxYh5sMh0NAJRD7ETpgfO88w',
    appId: '1:36544421419:web:13cf5df7beefe6bb23146e',
    messagingSenderId: '36544421419',
    projectId: 'apptinterview-9c173',
    authDomain: 'apptinterview-9c173.firebaseapp.com',
    databaseURL: 'https://apptinterview-9c173-default-rtdb.firebaseio.com',
    storageBucket: 'apptinterview-9c173.appspot.com',
    measurementId: 'G-WVZYTERHG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhMDdSGVW4YinmVmfbajGuzFe66d_prQ',
    appId: '1:36544421419:android:e9b303f175b920e323146e',
    messagingSenderId: '36544421419',
    projectId: 'apptinterview-9c173',
    databaseURL: 'https://apptinterview-9c173-default-rtdb.firebaseio.com',
    storageBucket: 'apptinterview-9c173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEHfRNOVmeNEeL0Uhmth6wFK5jZjwqbAs',
    appId: '1:36544421419:ios:54aca0357cbc2ee423146e',
    messagingSenderId: '36544421419',
    projectId: 'apptinterview-9c173',
    databaseURL: 'https://apptinterview-9c173-default-rtdb.firebaseio.com',
    storageBucket: 'apptinterview-9c173.appspot.com',
    androidClientId: '36544421419-js4p6m8s0d7r3n3l89m29jc6dl76f9hf.apps.googleusercontent.com',
    iosClientId: '36544421419-uf33npu7m8mh78s443k3vldp346uiict.apps.googleusercontent.com',
    iosBundleId: 'com.apptinterview.appTinterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEHfRNOVmeNEeL0Uhmth6wFK5jZjwqbAs',
    appId: '1:36544421419:ios:54aca0357cbc2ee423146e',
    messagingSenderId: '36544421419',
    projectId: 'apptinterview-9c173',
    databaseURL: 'https://apptinterview-9c173-default-rtdb.firebaseio.com',
    storageBucket: 'apptinterview-9c173.appspot.com',
    androidClientId: '36544421419-js4p6m8s0d7r3n3l89m29jc6dl76f9hf.apps.googleusercontent.com',
    iosClientId: '36544421419-uf33npu7m8mh78s443k3vldp346uiict.apps.googleusercontent.com',
    iosBundleId: 'com.apptinterview.appTinterview',
  );
}

//Platform  Firebase App Id
//web       1:36544421419:web:13cf5df7beefe6bb23146e
//android   1:36544421419:android:e9b303f175b920e323146e
//ios       1:36544421419:ios:54aca0357cbc2ee423146e
//macos     1:36544421419:ios:54aca0357cbc2ee423146e